/** Agent lifecycle status. */
export type AgentStatus = 'idle' | 'running' | 'ended' | 'failed';

/** Stage that produced a tool-call error event. */
export type ToolCallErrorTrigger = 'before' | 'calling' | 'after';

/** Function returned by event registration APIs to remove the listener. */
export type Unsubscribe = () => void;

/** JSON object used for tool parameter schemas. */
export type JsonObject = Record<string, unknown>;

/** Minimal schema contract required by framework tools. Zod object schemas satisfy it. */
export interface ToolParametersSchema {
  safeParse(data: unknown):
    | {
        success: true;
        data: unknown;
      }
    | {
        success: false;
        error: unknown;
      };
}

/** Status fields returned by Responses API output items. */
export type AgentResponseStatus = 'in_progress' | 'completed' | 'incomplete';

/** Text content for a framework-generated Responses input message. */
export interface AgentInputTextContentPart {
  type: 'input_text';
  text: string;
}

/** Image content uploaded through Files API and referenced in a Responses input message. */
export interface AgentInputImageContentPart {
  type: 'input_image';
  file_id: string;
  detail?: 'auto' | 'low' | 'high' | undefined;
}

/** Generic file content uploaded through Files API and referenced in a Responses input message. */
export interface AgentInputFileContentPart {
  type: 'input_file';
  file_id: string;
}

/** Video content uploaded through Files API and referenced in a Responses input message. */
export interface AgentInputVideoContentPart {
  type: 'input_video';
  file_id: string;
}

/** Audio content uploaded through Files API and referenced in a Responses input message. */
export interface AgentInputAudioContentPart {
  type: 'input_audio';
  file_id: string;
}

/** Content parts supported by framework-generated Responses input messages. */
export type AgentInputContentPart =
  | AgentInputTextContentPart
  | AgentInputImageContentPart
  | AgentInputFileContentPart
  | AgentInputVideoContentPart
  | AgentInputAudioContentPart;

/**
 * Input message generated by an Agent or appended by application code.
 *
 * Framework-generated input messages intentionally do not add response-only fields such as
 * `id` or `status`.
 */
export interface AgentInputMessage {
  role: 'system' | 'developer' | 'user';
  content: readonly AgentInputContentPart[];
  type?: 'message';
}

/** Reasoning summary entry returned inside an Ark Responses reasoning output item. */
export interface AgentReasoningSummary {
  type: 'summary_text';
  text: string;
  [key: string]: unknown;
}

/** Reasoning item returned by the model and preserved verbatim in conversation context. */
export interface AgentReasoningItem {
  type: 'reasoning';
  id?: string;
  summary?: readonly AgentReasoningSummary[];
  status?: AgentResponseStatus;
  [key: string]: unknown;
}

/** Text output item inside an assistant Responses message. */
export interface AgentOutputTextContentPart {
  type: 'output_text';
  text: string;
  [key: string]: unknown;
}

/** Assistant output message returned by the model and preserved verbatim. */
export interface AgentAssistantOutputMessage {
  type: 'message';
  role: 'assistant';
  id?: string;
  content: readonly (AgentOutputTextContentPart | Record<string, unknown>)[];
  status?: AgentResponseStatus;
  [key: string]: unknown;
}

/**
 * Function-call output item returned by the model.
 *
 * All response fields, including provider-specific additions, are kept when the item is
 * stored in context and sent on later turns.
 */
export interface AgentFunctionCallItem {
  type: 'function_call';
  call_id: string;
  name: string;
  arguments: string;
  id?: string;
  status?: AgentResponseStatus;
  [key: string]: unknown;
}

/** Other output item returned by an Ark Responses-compatible provider. */
export interface AgentUnknownResponseOutputItem {
  type: string;
  [key: string]: unknown;
}

/** A model Responses output item stored and resent without projection. */
export type AgentResponseOutputItem =
  | AgentReasoningItem
  | AgentAssistantOutputMessage
  | AgentFunctionCallItem
  | AgentUnknownResponseOutputItem;

/** Function result generated locally after executing a model function call. */
export interface AgentFunctionCallOutputItem {
  type: 'function_call_output';
  call_id: string;
  output: string;
}

/** Conversation item used as Responses `input` and persisted by Agent. */
export type AgentContext =
  | AgentInputMessage
  | AgentFunctionCallOutputItem
  | AgentResponseOutputItem;

/** One concrete procedure inside a skill handbook. */
export interface AgentSkillSop {
  description: string;
  content: string;
}

/**
 * Skill handbook metadata.
 *
 * Skills are surfaced through an internal system prompt. The model should call the
 * built-in `get-skill` tool to fetch full handbook content before following a SOP.
 */
export interface AgentSkill {
  name: string;
  description: string;
  systemContent?: string;
  sops?: AgentSkillSop[];
}

/** Context passed to dynamic tool description functions. */
export interface ToolDescriptionContext {
  /** Current skill handbooks visible to the Agent. */
  skills: readonly AgentSkill[];
  /** Sub-agent constructors available through the built-in `agent` tool. */
  subAgents: readonly AgentConstructor[];
  /** Active Responses input context, excluding transient system prompts. */
  context: readonly AgentContext[];
  /** Raw history, which may be initialized separately from active context. */
  history: readonly AgentContext[];
  /** User-supplied system prompts, excluding framework internal prompts. */
  systemPrompts: readonly string[];
  /** Tool currently being converted for the model. */
  tool: {
    name: string;
    parameters?: ToolParametersSchema;
  };
}

/** Static or runtime-generated tool description. */
export type ToolDescription = string | ((ctx: ToolDescriptionContext) => string);

/** Public tool definition used by the `@Tool` decorator and runtime tools. */
export interface ToolDefinition {
  name: string;
  description: ToolDescription;
  parameters?: ToolParametersSchema;
}

/** Runtime function invoked after arguments are parsed and validated. */
export type ToolHandler = (parameters: unknown) => unknown | Promise<unknown>;

/** Tool definition with a bound handler available on an Agent instance. */
export interface ToolRuntimeDefinition extends ToolDefinition {
  handler: ToolHandler;
}

/** Ark Responses-compatible function tool definition passed to Model implementations. */
export interface ModelToolDefinition {
  type: 'function';
  name: string;
  description: string;
  parameters: JsonObject;
  strict: true;
}

/** Request shape consumed by Responses-based Model implementations. */
export interface ModelResponsesRequest {
  input: readonly AgentContext[];
  tools: readonly ModelToolDefinition[];
}

/** Response shape returned by Responses-based Model implementations. */
export interface ModelResponsesResponse {
  output: readonly AgentResponseOutputItem[];
  raw?: unknown;
}

/** Instance contract required for sub-agent classes. */
export interface AgentInstance {
  init(): this;
  agent(message: string, stream?: boolean): Promise<AgentContext[]>;
}

/** Constructor contract accepted by `AgentOptions.subAgents`. */
export interface AgentConstructor<TAgent extends AgentInstance = AgentInstance> {
  new (options: AgentOptions): TAgent;
  readonly name: string;
  readonly description?: string;
  readonly toolsDefinition: readonly ToolDefinition[];
}

/** Options used to create an Agent or Agent subclass. */
export interface AgentOptions {
  /** Responses-based LLM adapter. `OpenAIModel` and custom `Model` subclasses satisfy this shape. */
  llm: {
    responses(request: ModelResponsesRequest): Promise<ModelResponsesResponse>;
  };
  /** Skill handbooks advertised through an internal system prompt. */
  skills?: readonly AgentSkill[];
  /** Sub-agent classes callable by the built-in `agent` tool. */
  subAgents?: readonly AgentConstructor[];
  /** User system prompts. Framework internal prompts are prepended before these. */
  systemPrompts?: readonly string[];
  /** Initial active Responses input context. Falls back to `initRawContext` when omitted. */
  initContext?: readonly AgentContext[];
  /** Initial raw history. Falls back to `initContext` when omitted. */
  initRawContext?: readonly AgentContext[];
  /** Optional hard stop for the agent loop. Omit for no explicit iteration limit. */
  maxIterations?: number;
}

/** Behavior controls for before/after tool-call listeners. */
export interface ToolEventOptions {
  /** Wait for the listener before continuing tool execution. */
  await?: boolean;
  /**
   * Only applies to before listeners: cancel the real tool call when the listener errors.
   * Async listener rejections can cancel only when `await` is also true.
   */
  errorCancel?: boolean;
}

/** Listener fired before a specific model-requested function is invoked. */
export type BeforeToolCallCallback = (
  parameters: unknown,
  message: AgentFunctionCallItem,
) => void | Promise<void>;

/** Listener fired after a specific tool handler returns. */
export type AfterToolCallCallback = (
  parameters: unknown,
  message: AgentFunctionCallItem,
  result: unknown,
) => void | Promise<void>;

/** Listener fired once per response, before its complete output array is persisted. */
export type ModelResponseCallback = (
  output: readonly AgentResponseOutputItem[],
) => void | Promise<void>;

/** Listener fired when before/calling/after tool handling reports an error. */
export type ToolCallErrorCallback = (
  name: string,
  triggerType: ToolCallErrorTrigger,
  error: unknown,
  parameters: unknown,
  message: AgentFunctionCallItem,
  result?: unknown,
) => void | Promise<void>;

/** Listener fired after the Agent enters the registered status. */
export type AgentStatusChangedCallback = (
  rawContext: readonly AgentContext[],
  context: readonly AgentContext[],
) => void | Promise<void>;

/** Listener fired for errors raised by `agent()`. */
export type AgentErrorCallback = (error: Error) => void | Promise<void>;
